// <auto-generated />
using System;
using System.Collections.Generic;
using CCG.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CCG.Core.Migrations
{
    [DbContext(typeof(CCGContext))]
    [Migration("20260415081833_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CCG.Core.Models.Article", b =>
                {
                    b.Property<string>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("article_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("ArticleId")
                        .HasName("articles_pkey");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.CartItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("amount");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "ProductId")
                        .HasName("cart_items_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("categories_pkey");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("order_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Discount")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12)")
                        .HasColumnName("discount");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receipt_id");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12)")
                        .HasColumnName("shipping_fee");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3)
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.HasKey("OrderId")
                        .HasName("orders_pkey");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("SupplierId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.OrderItem", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("text")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("amount");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12)")
                        .HasColumnName("price_at_purchase");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("order_items_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("product_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Cat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cat");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12)")
                        .HasColumnName("discount");

                    b.PrimitiveCollection<List<string>>("Features")
                        .HasColumnType("text[]")
                        .HasColumnName("features");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int>("InStock")
                        .HasColumnType("integer")
                        .HasColumnName("in_stock");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12)")
                        .HasColumnName("price");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("specs");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("ProductId")
                        .HasName("products_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.Receipt", b =>
                {
                    b.Property<string>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("receipt_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Discount")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12)")
                        .HasColumnName("discount");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<decimal>("Total")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12)")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ReceiptId")
                        .HasName("receipts_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.Review", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.HasKey("UserId", "ProductId")
                        .HasName("reviews_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_username");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("SupplierId")
                        .HasName("suppliers_pkey");

                    b.HasIndex(new[] { "Email" }, "uq_suppliers_email")
                        .IsUnique();

                    b.HasIndex(new[] { "NormalizedUsername" }, "uq_suppliers_normalized_username")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "uq_suppliers_username")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.SupplierToken", b =>
                {
                    b.Property<Guid>("SupplierTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_token_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("SupplierTokenId")
                        .HasName("supplier_tokens_pkey");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplier_tokens", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_username");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex(new[] { "Email" }, "uq_users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "NormalizedUsername" }, "uq_users_normalized_username")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "uq_users_username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.UserToken", b =>
                {
                    b.Property<Guid>("UserTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_token_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserTokenId")
                        .HasName("tokens_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("UserFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("UserId", "ProductId")
                        .HasName("user_favorites_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("user_favorites", (string)null);
                });

            modelBuilder.Entity("CCG.Core.Models.CartItem", b =>
                {
                    b.HasOne("CCG.Core.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("cart_items_product_id_fkey");

                    b.HasOne("CCG.Core.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("cart_items_user_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCG.Core.Models.Order", b =>
                {
                    b.HasOne("CCG.Core.Models.Receipt", "Receipt")
                        .WithMany("Orders")
                        .HasForeignKey("ReceiptId")
                        .IsRequired()
                        .HasConstraintName("orders_receipt_id_fkey");

                    b.HasOne("CCG.Core.Models.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("orders_supplier_id_fkey");

                    b.Navigation("Receipt");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CCG.Core.Models.OrderItem", b =>
                {
                    b.HasOne("CCG.Core.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("order_items_order_id_fkey");

                    b.HasOne("CCG.Core.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("order_items_product_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CCG.Core.Models.Product", b =>
                {
                    b.HasOne("CCG.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("products_category_id_fkey");

                    b.HasOne("CCG.Core.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("products_supplier_id_fkey");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CCG.Core.Models.Receipt", b =>
                {
                    b.HasOne("CCG.Core.Models.User", "User")
                        .WithMany("Receipts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("receipts_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCG.Core.Models.Review", b =>
                {
                    b.HasOne("CCG.Core.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("reviews_product_id_fkey");

                    b.HasOne("CCG.Core.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("reviews_user_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CCG.Core.Models.SupplierToken", b =>
                {
                    b.HasOne("CCG.Core.Models.Supplier", "Supplier")
                        .WithMany("SupplierTokens")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("supplier_tokens_supplier_id_fkey");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CCG.Core.Models.UserToken", b =>
                {
                    b.HasOne("CCG.Core.Models.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserFavorite", b =>
                {
                    b.HasOne("CCG.Core.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("user_favorites_product_id_fkey");

                    b.HasOne("CCG.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_favorites_user_id_fkey");
                });

            modelBuilder.Entity("CCG.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CCG.Core.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CCG.Core.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CCG.Core.Models.Receipt", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CCG.Core.Models.Supplier", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("SupplierTokens");
                });

            modelBuilder.Entity("CCG.Core.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Receipts");

                    b.Navigation("Reviews");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
